package com.example.dbzepisodesmovies;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class DataProvider {

	public static HashMap<String, List<String>> getInfoDB() {
		HashMap<String, List<String>> MoviesDetails = new HashMap<String, List<String>>();
		
		List<String> EPS = new ArrayList<String>();
		EPS.add("1. The Secret of the Dragon Balls");
		EPS.add("2. The Emperor's Quest");
		EPS.add("3. The Nimbus Cloud of Roshi");
		EPS.add("4. Oolong the Terrible");
		EPS.add("5. Yamcha the Desert Bandit");
		EPS.add("6. Keep an Eye on the Dragon Balls");
		EPS.add("7. The Ox King on Fire Mountain");
		EPS.add("8. The Kamehameha Wave");
		EPS.add("9. Boss Rabbit's Magic Touch");
		EPS.add("10. The Dragon Balls are Stolen!");
		EPS.add("11. The Penalty is Pinball");
		EPS.add("12. A Wish to the Eternal Dragon");
		EPS.add("13. The Legend of Goku");
		MoviesDetails.put("Emperor Pilaf Saga(1-13)", EPS);
		
		List<String> TS = new ArrayList<String>();
		TS.add("14. Goku's Rival");
		TS.add("15. Look Out For Launch");
		TS.add("16. Find That Stone!");
		TS.add("17. Milk Delivery");
		TS.add("18. The Turtle Hermit Way");
		TS.add("19. The Tornament Begins");
		TS.add("20. Elimination Round");
		TS.add("21. Smells Like Trouble");
		TS.add("22. Quarterfinals Begin");
		TS.add("23. Monster Beast Giran");
		TS.add("24. Frantic Attack");
		TS.add("25. Danger From Above");
		TS.add("26. The Grand Finals");
		TS.add("27. Number One Under The Moon?");
		TS.add("28. The Final Blow"); 
		MoviesDetails.put("Tournament Saga(14-28)", TS);

		List<String> RRAS = new ArrayList<String>();
		RRAS.add("29. The Roaming Lake");
		RRAS.add("30. Pilaf And Mystery Force");
		RRAS.add("31. Wedding Plans?");
		RRAS.add("32. The Flying Fortress Vanished!");
		RRAS.add("33. The Legend Of A Dragon");
		RRAS.add("34. Cruel General Red");
		RRAS.add("35. Cold Reception");
		RRAS.add("36. Major Metallitron");
		RRAS.add("37. Ninja Murasaki Is Coming");
		RRAS.add("38. Five Murasakis");
		RRAS.add("39. Mysterious Android No. 8");
		RRAS.add("40. Horrifying Buyon");
		RRAS.add("41. The Fall Of Muscle Tower");
		RRAS.add("42. The Secret Of Dr. Flappe");
		RRAS.add("43. A Trip To The City");
		RRAS.add("44. Master Thief, Hasky");
		RRAS.add("45. Danger In The Air");
		MoviesDetails.put("Red Ribbon Army Saga(29-45)",RRAS );
		
		List<String> GBS = new ArrayList<String>();
		GBS.add("46. Bulma's Bad Day");		
		GBS.add("47. Kame House Found!");
		GBS.add("48. Deep Blue Sea");
		GBS.add("49. Roshi Surprise");
		GBS.add("50. The Trap Is Sprung");
		GBS.add("51. Beware Of Robot");
		GBS.add("52. The Pirate Treasure");
		GBS.add("53. Blue, Black And Blue");
		GBS.add("54. Escape From Pirate Cave");
		GBS.add("55. Penguin Village");
		GBS.add("56. Strange Visitor");
		GBS.add("57. Arale Vs Blue");
		MoviesDetails.put("General Blue Saga(46-57)", GBS);
		
		List<String> CRS = new ArrayList<String>();
		CRS.add("58. The Land Of Korin");
		CRS.add("59. The Notorious Mercenary");
		CRS.add("60. Tao Attacks!");
		CRS.add("61. Korin Tower");
		CRS.add("62. Sacred Water");
		CRS.add("63. The Return Of Goku");
		CRS.add("64. The Last Of Mercenary Tao");
		CRS.add("65. Confront The Red Ribbon Army");
		CRS.add("66. A Real Blind");
		CRS.add("67. The End Of Commander Red");
		CRS.add("68. The Last Dragon Ball");
		MoviesDetails.put("Commander Red Saga(58-68)",CRS );
		
		List<String> FBS = new ArrayList<String>();
		FBS.add("69. Who Is Fortuneteller Baba?");
		FBS.add("70. We Are The Five Warriors");
		FBS.add("71. Deadly Battle");
		FBS.add("72. Goku's Turn Son Goku");
		FBS.add("73. The Devilmite Beam");
		FBS.add("74. The Mysterious Fifth Man");
		FBS.add("75. The Strong Ones");
		FBS.add("76. True Colors Of The Masked Man");
		FBS.add("77. Pilaf's Tactics");
		FBS.add("78. The Eternal Dragon Rises");
		FBS.add("79. Terror And Plague");
		FBS.add("80. Goku Vs Sky Dragon");
		FBS.add("81. Goku Goes To Demon Land");
		FBS.add("82. The Rampage Of InoShikaCho");
		MoviesDetails.put("Fortuneteller Baba Saga(69-82)", FBS);
		
	    List<String> TSS = new ArrayList<String>();
	    TSS.add("83. Which Way To Papaya Land?");
	    TSS.add("84. Rivals And Arrivals");
	    TSS.add("85. Preliminary Peril");
	    TSS.add("86. Then There Were Eight");
	    TSS.add("87. Yamcha Vs Tien");
	    TSS.add("88. Yamcha's Big Break");
	    TSS.add("89. Full-Moon Vengeance");
	    TSS.add("90. The Dondon Wave");
	    TSS.add("91. Counting Controversy!");
	    TSS.add("92. Goku Enters The Ring");
	    TSS.add("93. Tien Shinhan Vs Jackie Chun");
	    TSS.add("94. Stepping Down");
	    TSS.add("95. Goku Vs Krillin");
	    TSS.add("96. Tails's Tale");
	    TSS.add("97. Final Match: Goku Vs Tien");
	    TSS.add("98. Victory's Edge/Battle Power");
	    TSS.add("99. Tien's Insurrection");
	    TSS.add("100. The Spirit Canon");
	    TSS.add("101. The Fallen");
	    MoviesDetails.put("Tien Shinhan Saga(83-101)", TSS);
	    
	    List<String> KPS = new ArrayList<String>();
	    KPS.add("102. Enter King Piccolo");
	    KPS.add("103. Tambourine Attacks!");
	    KPS.add("104. Mark Of The Demon");
	    KPS.add("105. Here Comes Yajirobe");
	    KPS.add("106. Terrible Tambourine");
	    KPS.add("107. Tien's Atonement");
	    KPS.add("108. Goku's Revenge");
	    KPS.add("109. Goku Vs King Piccolo");
	    KPS.add("110. Piccolo Closes In");
	    KPS.add("111. Roshi's Gambit");
	    KPS.add("112. King Piccolo's Wish");
	    KPS.add("113. Siege On CHow Castle");
	    KPS.add("114. Conquest And Power");
	    KPS.add("115. Awaken Darkness");
	    KPS.add("116. A Taste Of Destiny");
	    KPS.add("117. The Ultimate Sacrifice");
	    KPS.add("118. Prelude To Vengeance");
	    KPS.add("119. Battle Cry");
	    KPS.add("120. Goku Strikes Back");
	    KPS.add("121. The Biggest Crisis");
	    KPS.add("122. The Final Showdown");
	    MoviesDetails.put("King Piccolo Saga(102-122)", KPS);
	    
	    List<String> PJS = new ArrayList<String>();
	    PJS.add("123. Lost And Found");
	    PJS.add("124. Temple And Clouds");
	    PJS.add("125. Earth's Guardian Emerges");
	    PJS.add("126. Eternal Dragon Resurrected");
	    PJS.add("127. Quicker Than Lightning");
	    PJS.add("128. Secret Of The Woods");
	    PJS.add("129. The Time Room");
	    PJS.add("130. Goku's Doll");
	    PJS.add("131. Walking Their Own Ways");
	    PJS.add("132. Hotter Than Lava");
	    PJS.add("133. Changes");
	    PJS.add("134. Preliminary Peril");
	    PJS.add("135. Battle Of The Eight");
	    PJS.add("136. Tien Shinhan Vs Mercenary");
	    PJS.add("137. Anonymous Proposal");
	    PJS.add("138. The Mysterious Hero");
	    PJS.add("139. Rematch");
	    PJS.add("140. Goku Gains Speed");
	    PJS.add("141. The Four Faces Of Tien");
	    PJS.add("142. Kami Vs Piccolo");
	    PJS.add("143. Battle For The Future");
	    PJS.add("144. Super Kamehameha");
	    PJS.add("145. Junior No More");
	    PJS.add("146. Goku's Trap");
	    PJS.add("147. Goku Hangs On");
	    PJS.add("148. The Victor");
	    PJS.add("149. Dress In Flames");
	    PJS.add("150. The Fire Eater");
	    PJS.add("151. Outrageous Octagon");
	    PJS.add("152. Mystery Of The Dark World");
	    PJS.add("153. The End, the Beginning");
	    MoviesDetails.put("Piccolo Jr. Saga(123-153)", PJS);
		
		return MoviesDetails;

	}
	
	public static HashMap<String, List<String>> getInfoDBZ() {
		HashMap<String, List<String>> MoviesDetails = new HashMap<String, List<String>>();
		
		List<String> SS = new ArrayList<String>();
		SS.add("1. The New Threat");
		SS.add("2. Reunions");
		SS.add("3. Unlikely Alliance");
		SS.add("4. Piccolo's Plan");
		SS.add("5. Gohan's Rage");
		SS.add("6. No Time Like The Present");
		SS.add("7. Day 1");
		SS.add("8. Gohan Goes The Bananas!");
		SS.add("9. The Strangest Robot");
		SS.add("10. A New Friend");
		SS.add("11. Terror On Arlia");
		SS.add("12. Global Training");
		SS.add("13. Goz And Mez");
		SS.add("14. Princess Snake");
		SS.add("15. Dueling Piccolos");
		SS.add("16. Plight Of The Children");
		SS.add("17. Pendulum Room Peril");
		SS.add("18. The End Of Snake Way");
		SS.add("19. Defying Gravity");
		SS.add("20. Goku's Ancestors");
		SS.add("21. Counting Down");
		SS.add("22. The Darkest Day");
		SS.add("23. Saibamen Attack");
		SS.add("24. The Power Of Nappa");
		SS.add("25. Sacrifice");
		SS.add("26. Nappa's Rampage");
		SS.add("27. Nimbus Speed");
		SS.add("28. Goku's Arrival");
		SS.add("29. Lesson Number One");
		SS.add("30. Goku Vs Vegeta");
		SS.add("31. Saiyan Sized Secret");
		SS.add("32. Spirit Bomb Away!");
		SS.add("33. Hero In The Shadows");
		SS.add("34. Krillin's Offensive");
		SS.add("35. Mercy");
		SS.add("36. Picking Up The Pieces");
		SS.add("37. Plans For Departure");
		SS.add("38. Nursing Wounds");
		SS.add("39. Friends Or Foes?");
		MoviesDetails.put("Saiyan Saga(1-39)", SS);
		
		List<String> NCGS = new ArrayList<String>();
		NCGS.add("40. Held Captive");
		NCGS.add("41. Look Out Below");
		NCGS.add("42. The Search Continues");
		NCGS.add("43. A Friendly Surprise");
		NCGS.add("44. Brood Of Evil");
		NCGS.add("45. Frieza Strikes!");
		NCGS.add("46. Defying Orders");
		NCGS.add("47. Namek's Defence");
		NCGS.add("48. The Hunted");
		NCGS.add("49. The Prince Fights Back");
		NCGS.add("50. Unexpected Problem");
		NCGS.add("51. Vegeta Has A Ball");
		NCGS.add("52. The Past And Future");
		NCGS.add("53. Zarbon's Surprise");
		NCGS.add("54. Guru's Gift");
		NCGS.add("55. Piccolo Vs Everyone");
		NCGS.add("56. Zarbon's Mission");
		NCGS.add("57. Gohan, the Hunted");
		NCGS.add("58. Unknown Enemies");
		NCGS.add("59. Destination:Guru");
		NCGS.add("60. Bulma's Big Day");
		NCGS.add("61. Hidden Power");
		NCGS.add("62. New Ally, New Problem");
		NCGS.add("63. Guldo's Mind Binds");
		NCGS.add("64. Recoome Unleashed");
		NCGS.add("65. Let The Battle Begin");
		NCGS.add("66. Goku's New Power");
		NCGS.add("67. A Legend Revealed");
		NCGS.add("68. Ginyu Assault");
		NCGS.add("69. Incredible Force!");
		NCGS.add("70. Frieza Approaches");
		NCGS.add("71. Ginyu is Goku");
		NCGS.add("72. Calling The Eternal Dragon");
		NCGS.add("73. Gohan-Defeat Your Dad");
		NCGS.add("74. Captain Ginyu... The Frog");
		MoviesDetails.put("Captain Ginyu Saga(40-74)", NCGS);
		
		List<String> FS = new ArrayList<String>();
		FS.add("75. Password Is Porunga");
		FS.add("76. Piccolo's Return");
		FS.add("77. The Fusion");
		FS.add("78. Fighting Power:One Million?");
		FS.add("79. Gohan Attacks");
		FS.add("80. Piccolo The Super-Namek");
		FS.add("81. Deja Vu");
		FS.add("82. Frieza's Second Transformation");
		FS.add("83. Another Transformation?");
		FS.add("84. Dende's Demise");
		FS.add("85. The Renewed Goku");
		FS.add("86. The End Of Vegeta");
		FS.add("87. The Ultimate Battle");
		FS.add("88. Clash Of The Super Powers");
		FS.add("89. Frieza's Boast");
		FS.add("90. Bold And Fearless");
		FS.add("91. Embodiment Of Fire");
		FS.add("92. Trump Card");
		FS.add("93. Keep The Chance Alive!!");
		FS.add("94. Power Of The Spirit");
		FS.add("95. Transformed At Last");
		FS.add("96. Explosion Of Anger");
		FS.add("97. Namek's Destruction?");
		FS.add("98. A Final Attack");
		FS.add("99. Approaching Destruction");
		FS.add("100. Gohan Returns");
		FS.add("101. The Last Wish");
		FS.add("102. Duel On A Vanishing Planet");
		FS.add("103. Pathos Of Frieza");
		FS.add("104. Frieza Defeated!!");
		FS.add("105. Mighty Blast Of Rage");
		FS.add("106. Namek's Explosion... Goku's End?");
		FS.add("107. Goku's Alive!!");
		MoviesDetails.put("Frieza Saga(75-107)", FS);
		
		List<String> GTAS = new ArrayList<String>();
		GTAS.add("108. The Heavens Tremble");
		GTAS.add("109. Black Fog Of Terror");
		GTAS.add("110. Battle On Kami's Lookout");
		GTAS.add("111. Fight With Piccolo");
		GTAS.add("112. Call For Restoration");
		GTAS.add("113. Suicidal Course");
		GTAS.add("114. Extreme Measures");
		GTAS.add("115. The World Awakens");
		GTAS.add("116. Brief Chance Of Victory");
		GTAS.add("117. Krillin's Proposal");
		GTAS.add("118. Frieza's Counterattack");
		GTAS.add("119. The Mysterious Youth");
		GTAS.add("120. Another Super Saiyan?");
		GTAS.add("121. Welcome Back Goku");
		GTAS.add("122. Mystery Revealed");
		GTAS.add("123. Goku's Special Technique");
		GTAS.add("124. Z Warriors Prepare");
		GTAS.add("125. Goku's Ordeal");
		GTAS.add("126. The Androids Appear");
		GTAS.add("127. A Handy Trick");
		GTAS.add("128. Double Trouble For Goku");
		GTAS.add("129. Upgrade To Super Saiyan");
		GTAS.add("130. The Secret Of Dr. Gero");
		GTAS.add("131. More Android?!");
		GTAS.add("132. Follow Dr. Gero");
		GTAS.add("133. Nightmare Comes True");
		GTAS.add("134. Goku's Assassin");
		GTAS.add("135. Deadly Beauty");
		GTAS.add("136. No Match For The Androids");
		GTAS.add("137. Last Ditch Effort");
		GTAS.add("138. Closing In");
		GTAS.add("139. Unwelcome Discovery");
		MoviesDetails.put("Android Sagas(108-139)", GTAS);
		
		List<String> CS = new ArrayList<String>();
		CS.add("140. Seized With Fear");
		CS.add("141. The Reunion");
		CS.add("142. Borrowed Powers");
		CS.add("143. His Name Is Cell");
		CS.add("144. Piccolo's Folly");
		CS.add("145. Laboratory Basement");
		CS.add("146. Our Hero Awakes");
		CS.add("147. Time Chamber");
		CS.add("148. The Monster Is Coming");
		CS.add("149. He's Here");
		CS.add("150. Up To Piccolo");
		CS.add("151. Silent Warrior");
		CS.add("152. Say Goodbye, 17");
		CS.add("153. Sacifice");
		CS.add("154. Saiyans Emerge");
		CS.add("155. Super Vegeta");
		CS.add("156. Bow To The Prince");
		CS.add("157. Hour Of Temptation");
		CS.add("158. Krillin's Decision");
		CS.add("159. The Last Defense");
		CS.add("160. Cell Is Complete");
		CS.add("161. Vegeta Must Pay");
		CS.add("162. Trunks Ascends");
		CS.add("163. Saving Throw");
		CS.add("164. Ghosts From Tomorrow");
		CS.add("165. The Cell Games");
		MoviesDetails.put("Perfect Cell Saga(140-165)",CS );
		
		List<String> CGS = new ArrayList<String>();
		CGS.add("166. What Is The Tournament?");
		CGS.add("167. The Doomsday Broadcast");
		CGS.add("168. Meet Me In The Ring");
		CGS.add("169. No Worries Here");
		CGS.add("170. A Girl Named Lime");
		CGS.add("171. Memories Of Gohan");
		CGS.add("172. A New Guardian");
		CGS.add("173. Dende's Dragon");
		CGS.add("174. The Puzzle Of General Tao");
		CGS.add("175. The Games Begin");
		CGS.add("176. Losers Fight First");
		CGS.add("177. Goku Vs Cell");
		CGS.add("178. Cell's Bag Of Tricks");
		CGS.add("179. No More Rules");
		CGS.add("180. The Fight Is Over");
		CGS.add("181. Faith In A Boy");
		CGS.add("182. Gohan's Desperate Plea");
		CGS.add("183. Android Explosion");
		CGS.add("184. Cell Juniors Attack!");
		CGS.add("185. The Unleashing And Awakening");
		CGS.add("186. The Unstoppable Gohan");
		CGS.add("187. Cell's Mighty Breakdown");
		CGS.add("188. A Hero's Farewell");
		CGS.add("189. Cell Returns!");
		CGS.add("190. The Horror Won't End");
		CGS.add("191. Save The World");
		CGS.add("192. Goku's Decision");
		CGS.add("193. One More Wish");
		CGS.add("194. Free The Future");
		MoviesDetails.put("Cell Games Saga(166-194)", CGS);
		
		List<String> GSWS = new ArrayList<String>();
		GSWS.add("195. Warriors Of The Dead");
		GSWS.add("196. Tounament Begins");
		GSWS.add("197. Water Fight");
		GSWS.add("198. Final Round");
		GSWS.add("199. Goku Vs Pikon");
		GSWS.add("200. Gohan Goes To High School");
		GSWS.add("201. I Am Saiyaman");
		GSWS.add("202. Gohan's First Date");
		GSWS.add("203. Rescue Videl");
		GSWS.add("204. Blackmail");
		GSWS.add("205. I'll Fight Too");
		GSWS.add("206. The Newest Super Saiyan");
		GSWS.add("207. Take Flight Videl");
		GSWS.add("208. Gather For The Tournament");
		GSWS.add("209. Camera Shy");
		GSWS.add("210. The World Tournament");
		GSWS.add("211. Trunks Vs Goten");
		GSWS.add("212. Best Of The Boys");
		GSWS.add("213. Big Trouble, Little Trunks");
		GSWS.add("214. Who Will Fight Who?");
		GSWS.add("215. Forfeit Of Piccolo!");
		GSWS.add("216. A Dark And Secret Power");
		GSWS.add("217. Videl Is Crushed");
		GSWS.add("218. Identities Revealed");
		GSWS.add("219. Energy Drain");
		MoviesDetails.put("World Tournament Saga(195-219)",GSWS );
		
		List<String> MBS = new ArrayList<String>();
		MBS.add("220. The Wizard's Curse");
		MBS.add("221. King of The Demons");
		MBS.add("222. Vegeta Attacks");
		MBS.add("223. Next Up, Goku");
		MBS.add("224. Battle Supreme");
		MBS.add("225. Eighteen Unmasks");
		MBS.add("226. Pay To Win");
		MBS.add("227. Heart Of A Villain");
		MBS.add("228. The Dark Prince Returns");
		MBS.add("229. Vegeta's Pride");
		MBS.add("230. The Long Awaited Fight");
		MBS.add("231. Magic Ball Of Buu");
		MBS.add("232. Buu Is Hatched");
		MBS.add("233. The Losses Begin");
		MBS.add("234. The Terror Of Majin Buu");
		MBS.add("235. Meal Time");
		MBS.add("236. The Warrior's Decision");
		MBS.add("237. Final Atonement");
		MBS.add("238. Evil Live On");
		MBS.add("239. Find The Dragon Balls");
		MBS.add("240. Revival");
		MBS.add("241. Global Announcement");
		MBS.add("242. Learn To Fuse");
		MBS.add("243. The Z Sword");
		MBS.add("244. Race To Capsule Corp.");
		MBS.add("245. Super Saiyan 3?!");
		MBS.add("246. Buu's Mutiny");
		MBS.add("247. The Fusion Dance");
		MBS.add("248. Goku's Time Is Up");
		MBS.add("249. Return To Other World");
		MBS.add("250. Out From The Broken Sword");
		MBS.add("251. Gotenks Is Born");
		MBS.add("252. Unlikely Friendship");
		MBS.add("253. I Kill No More");
		MoviesDetails.put("Majin Buu Saga(220-253)", MBS);
		
		List<String> FKBS = new ArrayList<String>();
		FKBS.add("254. The Evil Of Men");
		FKBS.add("255. Buu Against Buu");
		FKBS.add("256. Empty Planet");
		FKBS.add("257. Time Struggle");
		FKBS.add("258. Super Moves Of Gotenks");
		FKBS.add("259. Trapped In Forever");
		FKBS.add("260. Fedding Frenzy");
		FKBS.add("261. Gotenks Is Awesome");
		FKBS.add("262. Unlucky Break");
		FKBS.add("263. A Whole New Gohan");
		FKBS.add("264. Search For Survivors");
		FKBS.add("265. Majin Buu Transforms");
		FKBS.add("266. The Old Kai's Weapon");
		FKBS.add("267. Ready To Fuse?");
		FKBS.add("268. Union Of Rivals");
		FKBS.add("269. Meet Vegito");
		FKBS.add("270. Rip In The Universe");
		FKBS.add("271. Vegito...Downsized");
		FKBS.add("272. The Incredible Fighting Candy");
		FKBS.add("273. The Innards Of Buu");
		FKBS.add("274. Mind Trap");
		FKBS.add("275. Deadly Vision");
		FKBS.add("276. Evil Kid Buu");
		FKBS.add("277. End Of Earth");
		FKBS.add("278. True Saiyans Fight Alone");
		FKBS.add("279. Battle For The Universe Begins");
		FKBS.add("280. Vegeta's Respect");
		FKBS.add("281. Minute Of Desperation");
		FKBS.add("282. Old Buu Emerges");
		FKBS.add("283. Earth Reborn");
		FKBS.add("284. Call To Action");
		FKBS.add("285. People Of Reunite");
		FKBS.add("286. Spirit Bomb Triumphant");
		FKBS.add("287. Celebrations With Majin Buu");
		FKBS.add("288. He's Always Late");
		FKBS.add("289. Granddaughter Pan");
		FKBS.add("290. Buu's Reincarnation");
		FKBS.add("291. Goku's Next Journey");
		MoviesDetails.put("Kid Buu Saga(254-291)",FKBS );
		
		return MoviesDetails;
		
	}
	
	public static HashMap<String, List<String>> getInfoDBGT() {
		HashMap<String, List<String>> MoviesDetails = new HashMap<String, List<String>>();
		
		List<String> BSDBS = new ArrayList<String>();
		BSDBS.add("1. A Devasting Wish");
		BSDBS.add("2. Pan Blasts Off");
		BSDBS.add("3. Terror On Imecka");
		BSDBS.add("4. The Most Wanted List");
		BSDBS.add("5. Goku Vs Ledgic");
		BSDBS.add("6. Like Pulling Teeth");
		BSDBS.add("7. Trunks, The Bride");
		BSDBS.add("8. Whisker Power");
		BSDBS.add("9. Lord Luud");
		BSDBS.add("10. Dance And Attack");
		BSDBS.add("11. Lord Luud's Curse");
		BSDBS.add("12. The Last Oracle Of Luud"); 		
		BSDBS.add("13. The Man Behind The Curtain");
		BSDBS.add("14. The Battle Within");
		BSDBS.add("15. Beginning Of The End");
		MoviesDetails.put("Black Star DB Saga(1-15)", BSDBS);
		
		List<String> BS = new ArrayList<String>();
		BS.add("16. Giru's Checkered Past");
		BS.add("17. Pan's Gambit");
		BS.add("18. Unexpected Power");
		BS.add("19. A General Uprising");
		BS.add("20. The Source Of Rildo's Power");
		BS.add("21. A Secret Revealed");
		BS.add("22. The Baby Secret");
		BS.add("23. Hidden Danger");
		BS.add("24. Discovering The Truth");
		BS.add("25. Baby's Arrival");
		BS.add("26. Saiyan Hunting");
		BS.add("27. The Attack On Vegeta");
		BS.add("28. A Worldwide Problem");
		BS.add("29. The Fall Of The Saiyans");
		BS.add("30. The Game After Life");
		BS.add("31. Collapse From Within");
		BS.add("32. The Return Of Uub");
		BS.add("33. The Tail's Tale");
		BS.add("34. Back In The Game");
		BS.add("35. Goku's Ascension");
		BS.add("36. The Tuffle Gorilla Attacks");
		BS.add("37. Old Kai's Last Stand");
		BS.add("38. Family Bonds");
		BS.add("39. Baby Put To Rest");
		BS.add("40. Piccolo's Decision");
		MoviesDetails.put("Baby Saga(16-40)", BS);
		
		List<String> SAS = new ArrayList<String>();
		SAS.add("41. Curtain Call");
		SAS.add("42. A Dangerous Union");
		SAS.add("43. The Resurrection Of Cell And Frieza");
		SAS.add("44. 17 Times 2");
		SAS.add("45. Piccolo's Best Bet");
		SAS.add("46. Raising The Stakes");
		SAS.add("47. The Greatest Surprise");
		MoviesDetails.put("Super Android 17 Saga(41-47)", SAS);
		
		List<String> SDS = new ArrayList<String>();
		SDS.add("48. The Shadow Dragons");
		SDS.add("49. The Two-Star Dragon");
		SDS.add("50. The Five-Star Dragon");
		SDS.add("51. The Six-Star Dragon");
		SDS.add("52. The Seven-Star Dragon");
		SDS.add("53. Saying Goodbye");
		SDS.add("54. The Four-Star Dragon");
		SDS.add("55. The Heart Of Prince");
		SDS.add("56. The Three-Star Dragon");
		SDS.add("57. The One-Star Dragon");
		SDS.add("58. Shadow Dragons Unite");
		SDS.add("59. Super Saiyan 4 Vegeta");
		SDS.add("60. Super Saiyan 4 Fusion");
		SDS.add("61. The Limits Of Power");
		SDS.add("62. Rescue Goku");
		SDS.add("63. Universal Allies");
		SDS.add("64. Until We Meet Again");
		MoviesDetails.put("Shadow Dragon Saga(48-64)", SDS);
		
		return MoviesDetails;
		
	}
}
